### ISSUE TITLE
Feature 1: User can play a typing game

### ISSUE THREAD

**Issue by anthony-tran2** [anthony-tran2/AniTyper#1]
## 💰 Motivation

Anime fans can practice their typing using quotes from different animes.

## 📐 Plan

Create a typing game that allows anime fans practice typing and knowing when they typed characters correctly or incorrectly.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/85326711/127095803-e989cf10-193c-49e5-9a69-5390df0c428a.png)
![image](https://user-images.githubusercontent.com/85326711/127095853-134d58c0-202a-4823-ad93-afa99a1b7ede.png)

## ✅ Task List

- [x] Make the header
    - [x] create the logo
- [x] Add a div[data-view="typing-game"]
- [x] Using a temporary quote, create the styling for the typing game
- [x] Listen for 'load' event and load in a random quote to fill in the typing game every time the page loads in
- [x] Listen for 'keypress' 
    - [x] if it is the right word make the current character the 'correct' class and move on to the next character
    - [x] if it is a backspace remove the class from the current character and move back one space
    - [x] if it is the wrong word make the current character the 'wrong' class and move on to the next character
- [x] Verify that everytime you reload the page a new random quote is being used
- [x] Verify that the data-view is being stored in the data model and is stored in the local storage properly
- [x] Remove all CSS that is not being used
- [x] Test all functionality in a private browsing session
- [x] Fix all errors
