### ISSUE TITLE
Feature 2: User can restart typing game at any time

### ISSUE THREAD

**Issue by anthony-tran2** [anthony-tran2/AniTyper#2]
## 💰 Motivation

Anime fans can restart their typing game.

## 📐 Plan

Create a way for anime fans to restart their typing game whenever they want by pressing a single button

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/85326711/127097303-ed9f8c19-bf2d-4413-ba4b-c3acda832ade.png)
![image](https://user-images.githubusercontent.com/85326711/127097319-65f35126-b1f6-4ef6-be97-379cbebf627c.png)

## ✅ Task List

- [x] Add a statement below the game that lets people know that when they press tab, the game will restart with a new quote
- [x] Listen for the keydown event and when it is pressed, remove the old quote and it's other contents and insert a new one
- [x] Check to see that the feature is working properly
- [x] Remove all unused css and reorganize it if necessary
- [x] check all functionality in a private browser
