### ISSUE TITLE
Feature 3: User can see typing stats

### ISSUE THREAD

**Issue by anthony-tran2** [anthony-tran2/AniTyper#3]
## 💰 Motivation

Anime fans can see their typing statistics after the game is over.

## 📐 Plan

Create something new that will pop up above the typing game and display the player's wpm and accuracy above the game they just finished typing.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/85326711/127097584-451bdec0-cad6-435a-942a-9a8d3a12adee.png)
![image](https://user-images.githubusercontent.com/85326711/127097613-c4fa0271-5d66-4412-ba0a-cac4dbc7e711.png)

## ✅ Task List

- [x] Add temporary accuracy and wpm to style it on the webpage
- [x] when the first key is pressed start the timer
- [x] when the last key in the quote is pressed
    - [x] stop the timer
    - [x] unhide the divs containing the wpm and accuracy when the game is done
    - [x] calculate the accuracy and display it in its correct place
    - [x] calculate wpm and display it in its correct place ( wpm = ((charactersTyped / timePassed) / 5) / 60 )
- [x] When you restart the game
    - [x] reset the timer and other tracking values
