### ISSUE TITLE
Feature 4: User can select which anime their quote comes from

### ISSUE THREAD

**Issue by anthony-tran2** [anthony-tran2/AniTyper#4]
## 💰 Motivation

Anime fans can choose to type quotes from their favorite animes or ones that they've never heard of.

## 📐 Plan

Create a dropdown that allows the user to select which anime they want their quote to come from from the current slection of animes available in the api.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/85326711/127696674-bc95ce66-8a7e-4f29-a3bc-b62e94aa13fa.png)
![image](https://user-images.githubusercontent.com/85326711/127696740-8d1f983e-640d-42a1-bd62-ee41eb851660.png)

## ✅ Task List

- [x] create a form for selecting an anime
- [x] Use temporary anime titles to help style the select dropdown and the selecting elements
- [x] get list of anime from the api and sort it alphabetically
- [x] Add each anime to the dropdown for the datalist element
- [x] listen for the submit event on the form, prevent its default action, and choose a quote from only the selected anime when loading in the next quote
- [x] remove unecessary css
- [x] test functionality in a private browser
