### ISSUE TITLE
Feature 5: User can see information about the current quote

### ISSUE THREAD

**Issue by anthony-tran2** [anthony-tran2/AniTyper#5]
## 💰 Motivation

Anime fans can learn more about the current quote they are typing.

## 📐 Plan

Create a separate view for the user to go to to get a brief synopsis on the anime and along with its cover picture so they get a quick look at what the anime is about.

## 🖼️ Wireframes

![Screen Shot 2021-07-30 at 3 46 34 PM](https://user-images.githubusercontent.com/85326711/127718720-06c2180f-0b4e-4cdf-b3ce-74c1d690b709.png)
![Screen Shot 2021-07-30 at 3 46 26 PM](https://user-images.githubusercontent.com/85326711/127718726-7d184887-1e60-435b-ad23-41bb3ab8b895.png)

## ✅ Task List

- [x] Create a div[data-view="anime-info"]
- [x] Use temporary anime info to style webpage
- [x] Design 'anime info' button and 'back to game' button
- [x] add click event listener on anime info button and switch to anime-info view if clicked on
- [x] add click event listener on back to game button and switch to typing-game view if clicked on
- [x] if you reload the page while on anime view the page will keep all your info but if you reload while on the typing game you start a new game
